### ISSUE TITLE
cannot install on android

### ISSUE THREAD

**Issue by alainib** [hackdie/react-native-show-case#1]
hello 

i'm trying to test this package on android ( and ios after )

i get this error on windows 10 for android version : 

	Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
	java.lang.IllegalStateException: buildToolsVersion is not specified.
			at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
			at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)

	FAILURE: Build failed with an exception.

	* Where:
	Build file 'XXX\node_modules\react-native-show-case\android\build.gradle' line: 2

	* What went wrong:
	A problem occurred evaluating project ':react-native-show-case'.
	> Plugin with id 'kotlin-android' not found.

**I linked it but the first link of android step is not in MainActivity.java but MainApplication.java**

EDIT 1 
i followed this tutorial 
https://proandroiddev.com/react-native-bridge-with-kotlin-b2afde2f70b

i have now another error : 

	> Task :app:compileDebugJavaWithJavac
	xxx\android\app\src\main\java\com\org.xxx\MainApplication.java:20: error: package com.reactlibrary does not exist
	import com.reactlibrary.RNShowCasePackage;
						   ^
	xxx\android\app\src\main\java\com\org.xxx\MainApplication.java:47: error: cannot find symbol
							new RNShowCasePackage()
								^
	  symbol: class RNShowCasePackage
	2 errors

**Comment by hackdie** [comment]
` Plugin with id 'kotlin-android' not found.` are you using kotlin?

**Comment by alainib** [comment]
me not at all but in    node_modules\react-native-show-case\android\build.gradle : 

       apply plugin: 'kotlin-android'
       ...
       implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"



After installing kotlin my actual problem is 

          import com.reactlibrary.RNShowCasePackage;

**Comment by hackdie** [comment]
Yes, because this lib requires kotlin you need to have the lib in your bundle to support kotlin
